return {
	[1] = {
		Cost = 100_000,
		Rewards = {
			Multiplier = 1.5,
			LockBoost = 10,
			NewTools = {
				"Banana Peel",
				"Grapple Hook",
			},
		},
	},
	[2] = {
		Cost = 3_000_000,
		Rewards = {
			Multiplier = 2,
			LockBoost = 15,
			NewTools = {
				"Gravity Coil",
				"Gold Slap Hand",
			},
		},
	},
	[3] = {
		Cost = 25_000_000,
		Rewards = {
			Multiplier = 2.5,
			LockBoost = 20,
			NewTools = {
				"Invisibility Cloak",
			},
		},
	},
	[4] = {
		Cost = 200_000_000,
		Rewards = {
			Multiplier = 3,
			LockBoost = 30,
			NewTools = {
				"Magma Slap Hand",
			},
		},
	},
}
